package com.demo.fluid.util

object BundleKey {
    const val KEY_DUMMY_ENTITY = "KEY_DUMMY_ENTITY"
    const val KEY_FLUID_NAME_EDIT = "KEY_FLUID_NAME_EDIT"
    const val KEY_FLUID_NAME_ON_SCREEN = "KEY_FLUID_NAME_ON_SCREEN"
    const val KEY_FLUID_NAME_ADD_TEXT = "KEY_FLUID_NAME_ADD_TEXT"
    const val KEY_FLUID_NAME_PREVIEW = "KEY_FLUID_NAME_PREVIEW"
    const val KEY_WALLPAPER_WITH_TEXTVIEW = "KEY_WALLPAPER_WITH_TEXTVIEW"
}