package com.demo.fluid.framework.presentation.home

import com.demo.fluid.framework.presentation.model.HomeModel
import dagger.hilt.android.lifecycle.HiltViewModel
import pion.tech.fluid_wallpaper.framework.presentation.common.BaseViewModel
import javax.inject.Inject

@HiltViewModel
class HomeViewModel @Inject constructor(

) : BaseViewModel() {

   val listWallpaper = mutableListOf<HomeModel>()

    fun initData(){
        val arrayList = ArrayList<HomeModel>()
        arrayList.add(HomeModel("AbstractAdventure"))
        arrayList.add(HomeModel("BlindingBliss"))
        arrayList.add(HomeModel("BlinkingBeauty"))
        arrayList.add(HomeModel("BloodyBlue"))
        arrayList.add(HomeModel("BouncingBeach"))
        arrayList.add(HomeModel("BusyBrilliance"))
        arrayList.add(HomeModel("CalmChristmas"))
        arrayList.add(HomeModel("ClassyCombination"))
        arrayList.add(HomeModel("CloudyComposition"))
        arrayList.add(HomeModel("ComplexCells"))
        arrayList.add(HomeModel("CosmicChaos"))
        arrayList.add(HomeModel("CosmicCharm"))
        arrayList.add(HomeModel("CrazyColors"))
        arrayList.add(HomeModel("CreativeCanvas"))
        arrayList.add(HomeModel("DancingDna"))
        arrayList.add(HomeModel("DancingDna2"))
        arrayList.add(HomeModel("DancingInTheDark"))
        arrayList.add(HomeModel("DayDreaming"))
        arrayList.add(HomeModel("DimensionOfDepth"))
        arrayList.add(HomeModel("DisturbingDetails"))
        arrayList.add(HomeModel("EarthlyElements"))
        arrayList.add(HomeModel("ElectrifyingExperience"))
        arrayList.add(HomeModel("ExoticEnergy"))
        arrayList.add(HomeModel("ExoticEnergy2"))
        arrayList.add(HomeModel("ExoticEnergy3"))
        arrayList.add(HomeModel("ExoticEnergy4"))
        arrayList.add(HomeModel("ExoticEnergy5"))
        arrayList.add(HomeModel("ExoticEnergy6"))
        arrayList.add(HomeModel("FadingForms"))
        arrayList.add(HomeModel("FantasticFilaments"))
        arrayList.add(HomeModel("FantasticFilaments2"))
        arrayList.add(HomeModel("FantasyFireworks"))
        arrayList.add(HomeModel("FireAndFlame"))
        arrayList.add(HomeModel("FireAndFlame2"))
        arrayList.add(HomeModel("FireFlies"))
        arrayList.add(HomeModel("FireFlies2"))
        arrayList.add(HomeModel("FireFlies3"))
        arrayList.add(HomeModel("FireFlies4"))
        arrayList.add(HomeModel("FireFlies5"))
        arrayList.add(HomeModel("FireFlies6"))
        arrayList.add(HomeModel("FireFlies7"))
        arrayList.add(HomeModel("FireFlies8"))
        arrayList.add(HomeModel("FireFlies9"))
        arrayList.add(HomeModel("FireFlies10"))
        arrayList.add(HomeModel("FlashyFluids"))
        arrayList.add(HomeModel("FloatingFlames"))
        arrayList.add(HomeModel("FloatingFlames2"))
        arrayList.add(HomeModel("FloatingFlames3"))
        arrayList.add(HomeModel("FloatingFlames4"))
        arrayList.add(HomeModel("FloatingFlames5"))
        arrayList.add(HomeModel("FloatingFlames6"))
        arrayList.add(HomeModel("FloatingFlames7"))
        arrayList.add(HomeModel("FloatingFlames8"))
        arrayList.add(HomeModel("FloatingFlames9"))
        arrayList.add(HomeModel("FloatingFlames10"))
        arrayList.add(HomeModel("FloatingFlames11"))
        arrayList.add(HomeModel("FloatingFlames12"))
        arrayList.add(HomeModel("FreakyFun"))
        arrayList.add(HomeModel("GentleGlow"))
        arrayList.add(HomeModel("GirlsGame"))
        arrayList.add(HomeModel("GleefulGlimmers"))
        arrayList.add(HomeModel("GlimmerGlow"))
        arrayList.add(HomeModel("GloriousGalaxies"))
        arrayList.add(HomeModel("GlowingGlare"))
        arrayList.add(HomeModel("GrainyGreatness"))
        arrayList.add(HomeModel("GravityGame"))
        arrayList.add(HomeModel("ImpressionistImage"))
        arrayList.add(HomeModel("IncredibleInk"))
        arrayList.add(HomeModel("JitteryJello"))
        arrayList.add(HomeModel("KittyKat"))
        arrayList.add(HomeModel("LakeOfLava"))
        arrayList.add(HomeModel("LakeOfLava2"))
        arrayList.add(HomeModel("LakeOfLava3"))
        arrayList.add(HomeModel("LakeOfLava4"))
        arrayList.add(HomeModel("LakeOfLava5"))
        arrayList.add(HomeModel("LakeOfLava6"))
        arrayList.add(HomeModel("LakeOfLava7"))
        arrayList.add(HomeModel("LakeOfLava8"))
        arrayList.add(HomeModel("LifeOfLights"))
        arrayList.add(HomeModel("LifeOfLightsOld"))
        arrayList.add(HomeModel("LovelyLiquid"))
        arrayList.add(HomeModel("MagicMarker"))
        arrayList.add(HomeModel("MagicMirror"))
        arrayList.add(HomeModel("MagicTrailByToni"))
        arrayList.add(HomeModel("MagicTrailByToni2"))
        arrayList.add(HomeModel("MagicTrailByToni3"))
        arrayList.add(HomeModel("MagicTrailByToni4"))
        arrayList.add(HomeModel("MoltenMetal"))
        arrayList.add(HomeModel("NefariousNeons"))
        arrayList.add(HomeModel("ParticleParty"))
        arrayList.add(HomeModel("PeacefulPond"))
        arrayList.add(HomeModel("RadioactiveRumble"))
        arrayList.add(HomeModel("RandomRemarkability"))
        arrayList.add(HomeModel("ShadowAndShade"))
        arrayList.add(HomeModel("ShinySwirls"))
        arrayList.add(HomeModel("SilkySmooth"))
        arrayList.add(HomeModel("SlickSlime"))
        arrayList.add(HomeModel("SomethingStrange"))
        arrayList.add(HomeModel("SteadySea"))
        arrayList.add(HomeModel("StrangeSubstance"))
        arrayList.add(HomeModel("SubtleSetting"))
        arrayList.add(HomeModel("SuperSmoke"))
        arrayList.add(HomeModel("SwirlySparkles"))
        arrayList.add(HomeModel("TanglingTrails"))
        arrayList.add(HomeModel("TransientThoughts"))
        arrayList.add(HomeModel("TrippyTint"))
        arrayList.add(HomeModel("UniquelyUnreal"))
        arrayList.add(HomeModel("VanishingVista"))
        arrayList.add(HomeModel("VIP1"))
        arrayList.add(HomeModel("VIP2"))
        arrayList.add(HomeModel("VIP3"))
        arrayList.add(HomeModel("VIP4"))
        arrayList.add(HomeModel("VIP5"))
        arrayList.add(HomeModel("VIP6"))
        arrayList.add(HomeModel("VIP7"))
        arrayList.add(HomeModel("VIP8"))
        arrayList.add(HomeModel("VIP9"))
        arrayList.add(HomeModel("VIP10"))
        arrayList.add(HomeModel("WavyWinter"))
        arrayList.add(HomeModel("WeirdWater"))
        arrayList.add(HomeModel("WizardWand"))
        arrayList.add(HomeModel("WobblyWorld"))
        arrayList.add(HomeModel("WonderfulWaves"))
        arrayList.add(HomeModel("WonderfulWhirls"))
        listWallpaper.addAll(arrayList)
    }
}