package com.demo.fluid.activity.home;

import androidx.lifecycle.ViewModel;
import java.util.ArrayList;

public class HomeViewModel extends ViewModel {
    public static ArrayList<HomeModel> listDataWallpaper = new ArrayList<>();
    private final ArrayList<HomeModel> myArrayList;

    public HomeViewModel() {
        ArrayList<HomeModel> arrayList = new ArrayList<>();
        this.myArrayList = arrayList;
        arrayList.add(new HomeModel("AbstractAdventure", "yes"));
        arrayList.add(new HomeModel("BlindingBliss", "no"));
        arrayList.add(new HomeModel("BlinkingBeauty", "no"));
        arrayList.add(new HomeModel("BloodyBlue", "yes"));
        arrayList.add(new HomeModel("BouncingBeach", "no"));
        arrayList.add(new HomeModel("BusyBrilliance", "no"));
        arrayList.add(new HomeModel("CalmChristmas", "no"));
        arrayList.add(new HomeModel("ClassyCombination", "no"));
        arrayList.add(new HomeModel("CloudyComposition", "yes"));
        arrayList.add(new HomeModel("ComplexCells", "no"));
        arrayList.add(new HomeModel("CosmicChaos", "no"));
        arrayList.add(new HomeModel("CosmicCharm", "yes"));
        arrayList.add(new HomeModel("CrazyColors", "no"));
        arrayList.add(new HomeModel("CreativeCanvas", "no"));
        arrayList.add(new HomeModel("DancingDna", "yes"));
        arrayList.add(new HomeModel("DancingDna2", "no"));
        arrayList.add(new HomeModel("DancingInTheDark", "yes"));
        arrayList.add(new HomeModel("DayDreaming", "no"));
        arrayList.add(new HomeModel("DimensionOfDepth", "no"));
        arrayList.add(new HomeModel("DisturbingDetails", "no"));
        arrayList.add(new HomeModel("EarthlyElements", "yes"));
        arrayList.add(new HomeModel("ElectrifyingExperience", "no"));
        arrayList.add(new HomeModel("ExoticEnergy", "no"));
        arrayList.add(new HomeModel("ExoticEnergy2", "no"));
        arrayList.add(new HomeModel("ExoticEnergy3", "yes"));
        arrayList.add(new HomeModel("ExoticEnergy4", "no"));
        arrayList.add(new HomeModel("ExoticEnergy5", "no"));
        arrayList.add(new HomeModel("ExoticEnergy6", "no"));
        arrayList.add(new HomeModel("FadingForms", "no"));
        arrayList.add(new HomeModel("FantasticFilaments", "no"));
        arrayList.add(new HomeModel("FantasticFilaments2", "no"));
        arrayList.add(new HomeModel("FantasyFireworks", "no"));
        arrayList.add(new HomeModel("FireAndFlame", "no"));
        arrayList.add(new HomeModel("FireAndFlame2", "no"));
        arrayList.add(new HomeModel("FireFlies", "yes"));
        arrayList.add(new HomeModel("FireFlies2", "no"));
        arrayList.add(new HomeModel("FireFlies3", "no"));
        arrayList.add(new HomeModel("FireFlies4", "no"));
        arrayList.add(new HomeModel("FireFlies5", "yes"));
        arrayList.add(new HomeModel("FireFlies6", "no"));
        arrayList.add(new HomeModel("FireFlies7", "no"));
        arrayList.add(new HomeModel("FireFlies8", "yes"));
        arrayList.add(new HomeModel("FireFlies9", "no"));
        arrayList.add(new HomeModel("FireFlies10", "no"));
        arrayList.add(new HomeModel("FlashyFluids", "no"));
        arrayList.add(new HomeModel("FloatingFlames", "yes"));
        arrayList.add(new HomeModel("FloatingFlames2", "no"));
        arrayList.add(new HomeModel("FloatingFlames3", "no"));
        arrayList.add(new HomeModel("FloatingFlames4", "no"));
        arrayList.add(new HomeModel("FloatingFlames5", "no"));
        arrayList.add(new HomeModel("FloatingFlames6", "yes"));
        arrayList.add(new HomeModel("FloatingFlames7", "no"));
        arrayList.add(new HomeModel("FloatingFlames8", "no"));
        arrayList.add(new HomeModel("FloatingFlames9", "no"));
        arrayList.add(new HomeModel("FloatingFlames10", "yes"));
        arrayList.add(new HomeModel("FloatingFlames11", "no"));
        arrayList.add(new HomeModel("FloatingFlames12", "no"));
        arrayList.add(new HomeModel("FreakyFun", "yes"));
        arrayList.add(new HomeModel("GentleGlow", "no"));
        arrayList.add(new HomeModel("GirlsGame", "no"));
        arrayList.add(new HomeModel("GleefulGlimmers", "no"));
        arrayList.add(new HomeModel("GlimmerGlow", "no"));
        arrayList.add(new HomeModel("GloriousGalaxies", "no"));
        arrayList.add(new HomeModel("GlowingGlare", "no"));
        arrayList.add(new HomeModel("GrainyGreatness", "no"));
        arrayList.add(new HomeModel("GravityGame", "yes"));
        arrayList.add(new HomeModel("ImpressionistImage", "no"));
        arrayList.add(new HomeModel("IncredibleInk", "no"));
        arrayList.add(new HomeModel("JitteryJello", "yes"));
        arrayList.add(new HomeModel("KittyKat", "no"));
        arrayList.add(new HomeModel("LakeOfLava", "no"));
        arrayList.add(new HomeModel("LakeOfLava2", "no"));
        arrayList.add(new HomeModel("LakeOfLava3", "yes"));
        arrayList.add(new HomeModel("LakeOfLava4", "no"));
        arrayList.add(new HomeModel("LakeOfLava5", "no"));
        arrayList.add(new HomeModel("LakeOfLava6", "no"));
        arrayList.add(new HomeModel("LakeOfLava7", "no"));
        arrayList.add(new HomeModel("LakeOfLava8", "yes"));
        arrayList.add(new HomeModel("LifeOfLights", "no"));
        arrayList.add(new HomeModel("LifeOfLightsOld", "no"));
        arrayList.add(new HomeModel("LovelyLiquid", "no"));
        arrayList.add(new HomeModel("MagicMarker", "yes"));
        arrayList.add(new HomeModel("MagicMirror", "no"));
        arrayList.add(new HomeModel("MagicTrailByToni", "no"));
        arrayList.add(new HomeModel("MagicTrailByToni2", "no"));
        arrayList.add(new HomeModel("MagicTrailByToni3", "no"));
        arrayList.add(new HomeModel("MagicTrailByToni4", "yes"));
        arrayList.add(new HomeModel("MoltenMetal", "no"));
        arrayList.add(new HomeModel("NefariousNeons", "no"));
        arrayList.add(new HomeModel("ParticleParty", "yes"));
        arrayList.add(new HomeModel("PeacefulPond", "no"));
        arrayList.add(new HomeModel("RadioactiveRumble", "no"));
        arrayList.add(new HomeModel("RandomRemarkability", "no"));
        arrayList.add(new HomeModel("ShadowAndShade", "no"));
        arrayList.add(new HomeModel("ShinySwirls", "yes"));
        arrayList.add(new HomeModel("SilkySmooth", "no"));
        arrayList.add(new HomeModel("SlickSlime", "no"));
        arrayList.add(new HomeModel("SomethingStrange", "no"));
        arrayList.add(new HomeModel("SteadySea", "yes"));
        arrayList.add(new HomeModel("StrangeSubstance", "no"));
        arrayList.add(new HomeModel("SubtleSetting", "no"));
        arrayList.add(new HomeModel("SuperSmoke", "yes"));
        arrayList.add(new HomeModel("SwirlySparkles", "no"));
        arrayList.add(new HomeModel("TanglingTrails", "no"));
        arrayList.add(new HomeModel("TransientThoughts", "no"));
        arrayList.add(new HomeModel("TrippyTint", "no"));
        arrayList.add(new HomeModel("UniquelyUnreal", "yes"));
        arrayList.add(new HomeModel("VanishingVista", "no"));
        arrayList.add(new HomeModel("VIP1", "no"));
        arrayList.add(new HomeModel("VIP2", "yes"));
        arrayList.add(new HomeModel("VIP3", "no"));
        arrayList.add(new HomeModel("VIP4", "no"));
        arrayList.add(new HomeModel("VIP5", "yes"));
        arrayList.add(new HomeModel("VIP6", "no"));
        arrayList.add(new HomeModel("VIP7", "no"));
        arrayList.add(new HomeModel("VIP8", "no"));
        arrayList.add(new HomeModel("VIP9", "no"));
        arrayList.add(new HomeModel("VIP10", "yes"));
        arrayList.add(new HomeModel("WavyWinter", "no"));
        arrayList.add(new HomeModel("WeirdWater", "no"));
        arrayList.add(new HomeModel("WizardWand", "yes"));
        arrayList.add(new HomeModel("WobblyWorld", "no"));
        arrayList.add(new HomeModel("WonderfulWaves", "no"));
        arrayList.add(new HomeModel("WonderfulWhirls", "yes"));
    }

    public void setData() {
        listDataWallpaper.clear();
        listDataWallpaper.addAll(this.myArrayList);
    }
}
